package com.tomerpacific.caridentifier

fun getCarManufacturer(manufacturer: String): String {
    return when (manufacturer) {
        "סאאב" -> "Saab"
        "סאנגיונג" -> "Sangyong"
        "טויוטה" -> "Toyota"
        "מאזדה" -> "Mazda"
        "יונדאי" -> "Hyundai"
        "קיה" -> "Kia"
        "ניסאן" -> "Nissan"
        "מיצובישי" -> "Mitsubishi"
        "פורד" -> "Ford"
        "שברולט" -> "Chevrolet"
        "הונדה" -> "Honda"
        "פולקסווגן" -> "Volkswagen"
        "סובארו" -> "Subaru"
        "סקודה" -> "Skoda"
        "רנו" -> "Renault"
        "פיג'ו" -> "Peugeot"
        "סיטרואן" -> "Citroën"
        "ב.מ.וו" -> "BMW"
        "מרצדס" -> "Mercedes"
        "אאודי" -> "Audi"
        "וולוו" -> "Volvo"
        "ג'יפ" -> "Jeep"
        "טסלה" -> "Tesla"
        "סוזוקי" -> "Suzuki"
        "פיאט" -> "Fiat"
        "אופל" -> "Opel"
        "סיאט" -> "Seat"
        "לקסוס" -> "Lexus"
        "אינפיניטי" -> "Infiniti"
        "לנד רובר" -> "Land Rover"
        "יגואר" -> "Jaguar"
        "דאצ'יה" -> "Dacia"
        "אם.ג'י" -> "MG"
        "פורשה" -> "Porsche"
        "מיני" -> "Mini"
        else -> "Unknown Manufacturer"
    }
}
