name: Android Build

on: pull_request

jobs:
  build:
    lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'       
          cache: 'gradle'

      - name: Run detekt
        run: ./gradlew detekt

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble